### ISSUE TITLE
[REQUEST] Add additional UI to distinguish a new update vs unread chapter

### ISSUE THREAD

**Issue by stan-snf** [Paperback-iOS/app#123]
**Description**
Add a mark (dot, highlight, etc.) beside the chapter that indicates the chapters that have just been added to distinguish it from just regular unread chapters

**How would it improve the App?**
Because some extra content (usually the ".5" chapters) are added later than some current chapters, and this makes it easier to spot.

**Additional context**
on request

**Comment by ConradWeiser** [comment]
This is difficult to perform at the moment, because when a source returns what has been updated, it simply returns the MangaID. A chapter ID was not returned to guarantee that you're marking the correct objects as a new update. 

Now that sources are more promised-based, we have the flexibility to ensure such a thing (probably). We'll see where this sits in the project scope.
