### ISSUE TITLE
[BUG] Language

### ISSUE THREAD

**Issue by Sarge58** [Paperback-iOS/app#165]
The bug itself is the content language being reset every time I close and reopen the app.
It resets to all languages even though I’ve set it to English and saved multiple times

Version-
0.2.2

**Comment by FramboisePi** [comment]
Hi @Sarge58,

Did you try to connect you on the app with your MangaDex account, checking `Remember me`? If yes, check your email adress is verified on MangaDex. 
That usually does solve the issue. 

I suggest you to check [My content settings are reset everytime I open the app](https://paperback.moe/help/faq/#my-content-settings-are-reset-everytime-i-open-the-app) faq section.
If that does solve the issue, you should close it in order to facilitate issues tracking.

**Comment by ConradWeiser** [comment]
Closing this support ticket as it's a few months old without further response.
