### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by bubop** [Paperback-iOS/app#175]
**Describe the bug**
app crashes when on discover page

**To Reproduce**
open the app, it crashes
go to discover from a different tab, it crashes
basically if you dont go to a different tab fast enough upon opening the app it’ll crash everytime (at least it do for me
**Expected behaviour**
be able to actually look through manga through that tab

**App Version**
v0.3.0-b8.1.2 
iOS 14

**Sources**
mangadex
mangasee
nhentai
webtoon
toonily
isekaiscan

**Comment by ConradWeiser** [comment]
This crash is caused by Toonily. I do not believe that this is an app problem.
Since then, Toonily has been updated with the section causing the crash removed temporarily until it's fixed. 

Reinstalling the app should fix your problem. You are free to install Toonily again, and not have this problem occur again.
