### ISSUE TITLE
[BUG] Half chapter skipped

### ISSUE THREAD

**Issue by P2ON** [Paperback-iOS/app#182]
**Describe the bug**

For the past few days, when I move on to the next chapter. I start halfway through the chapter and I have to go all the way to the top. Sometimes it happens only with one chapter of a manga and sometimes it happens on all the chapters of another manga. 

As an example, I'm reading Shamo (source: Mangadex) and it happens in almost every chapter. 

**App Version**

10.0.7

**Comment by ConradWeiser** [comment]
Hi @P2ON, Version 10 of the app is really darned old!
This issue is fixed in the latest TestFlight build.

https://testflight.apple.com/join/hLKHUuEr

All the information you need to opt-in to the beta version should be on this website! (You'll have to download Apple's TestFlight app) - If you have any questions, please feel free to re-open this issue and ask, or message us on our discord.
