### ISSUE TITLE
[BUG] Crash when opening Bakuman vol1 ch1 on Mangadex

### ISSUE THREAD

**Issue by eramdam** [Paperback-iOS/app#196]
**Describe the bug**
What the title says

**To Reproduce**
- Search for Bakuman on MangaDex
- Open a chapter from MangaPlus
- Reader tries to open
- App crashes

**Expected behaviour**

**App Version**
v0.3.0-b11.0.5 on iOS 14 stable

**Screenshots**
Demo -> https://www.dropbox.com/s/5zt6dd4j44093tp/paperback-mangadex-mangaplus-crash.mp4?dl=0

**Comment by ConradWeiser** [comment]
Unfortunately, Bakuman is a Viz Media title. Viz content is blocked on the MangaDex app due to legal issues. 
This shouldn't be crashing the app however, I've made a quick bugfix for the next patch which fixes the app from failing. Instead, pages simply won't load (as it's blocked unfortunately)

I'll discuss with the others a way to alert users if they're looking at some content which is blocked on MangaDex.

If you'd like to read Bakuman, other sources do not have this same block list. Give MangaLife a try!

**Comment by eramdam** [comment]
@ConradWeiser Yeah that's what I suspected. What's odd however is that the same chapters by `SleepyFans` do not crash the app?

**Comment by ConradWeiser** [comment]
Yeah, not quite sure what’s going on there. The crash fix is in the next beta release so the problem should go away.

To be honest I don’t really know how the mangadex source works. I’ve never really looked at it since it’s built into things in a weird way.
That’s the only source I’ve seen this issue from though.

Ah well. The problem as a whole should be fixed when mangadex is moved away from as a central thing, which is an eventual plan.
