### ISSUE TITLE
[REQUEST] Automatic reading mode

### ISSUE THREAD

**Issue by nevoreko** [Paperback-iOS/app#23]
Having the reading mode adapting automatically to the type of the page structure (right to left for manga, long stripe for manhwa..)

**Comment by ConradWeiser** [comment]
While we are able to tell what a manga type is with the longStrip boolean flag given to us by the sources, this would need the attached functionality where if a user overrides the mode (For instance, a manga is Horizontal, and the user selects longstrip instead) - it should remember the users choice for that title. 

Although then again, if you're flagging something normal as longstrip incorrectly, that's the source developer's realm to fix. If we can trust that boolean, this might be a good idea.

**Comment by axeII** [comment]
I think it would be better (especially for iPad) So when user is using vertical position - switch automatically to single page mode, however in landscape mode you could automatically switch to double page. 

I think manga rock was working like this and it was super useful.

**Comment by ConradWeiser** [comment]
A lot of users wouldn't like an automatic switch like that. A compromise plan which we're likely going to implement: When you set MangaA to vertical mode, and MangaB to horizontal mode, whenever you open up that title again, it will ALWAYS go back to whatever you had it set like previously.

That way once you set something once, it will always be on that reader mode until you change it again.

**Comment by axeII** [comment]
I agree that this feature could annoy iPhone users, since it’s  much smaller device where any rotation could be accidental. 

However iPad is much larger device and if you rotate iPad you most likely do it on purpose. Plus in landscape mode device feels like a double paged book. I just checked and same behavior (on iPad only) has “Books” application from Apple. 

I still think this automatic option would make reading manga much easier for iPad users rather than do it manually.
> A lot of users wouldn't like an automatic switch like that

You could add switch option to turn it off or on.

**Comment by ConradWeiser** [comment]
The default reader options are configurable in the app-settings. The 'prefered' reading style is already defined by the user. General survey of users says that people tend to stick to their favorite default, unless it needs to change because it's a longstrip manhwa of some kind. A feature which the app already handles. (If longstrip, the system defaults to the vertical reader as it won't render right on horizontal)

> You could add switch option to turn it off or on.

I suppose so, though we're aiming for simplicity with Paperback. Tachiyomi on the Android has taken a different approach. Extremely customizable, but the amount of settings, buttons and toggles can be a little intimidating. 

Our approach is necessity and comfort. 

Will this feature as a 'toggle' in the settings make the app more complicated and stray away from this 'simplicity' goal? ... It might not, actually. We'll keep this issue open. If we get more users expressing interest in what you've described, we'll consider implementation. 👍

**Comment by FaizanDurrani** [comment]
Added in 0.4.0 (2.2.9-Alpha)
