### ISSUE TITLE
[REQUEST] Ability to choose manga providers.

### ISSUE THREAD

**Issue by xKings** [Paperback-iOS/app#242]
**Description**
Essentially, Like a menu that will allow us to choose the manga provider. Example, Tokyo Ghoul on MangaDex has multiple providers, so we should be able to choose which provider we want. Tokyo Ghoul has multiple providers and i prefer Twisted Hel Scan but some chapters have another provider. I would liek a way to sort through these providers if possible.

**How would it improve the App?**
It would eliminate duplicate chapters showing up and also allow users to choose the providers they prefer.

**Additional context**
![image](https://user-images.githubusercontent.com/42078899/107105326-a81b3000-67f3-11eb-9736-29cad8cfae85.jpeg)
This photo shows the duplicate chapters because there are 2 versions of the manga chapter. One by "MangaPlus" and the other by "LazyA**Scans".

**Comment by xKings** [comment]
**Extra Screenshots**
![image](https://user-images.githubusercontent.com/42078899/107105465-7d7da700-67f4-11eb-91d6-aa3ff7e8fb36.jpeg)
 This is on the MangaDex website and you can see the chapters are provided by Twisted Hel Scan, which is what I would like on the app as well, but instead I'm getting another provider which I don't like.

**Comment by FaizanDurrani** [comment]
![image](https://user-images.githubusercontent.com/4832034/107116526-9f7b3600-6895-11eb-9ea3-62d8b8d1003d.png)
The app is displaying the chapters correctly, Twisted Hel Scans started uploading from Vol 1 Ch 7 on MangaDex if you go into settings > chapter list sort in the app you can change the chapterlist sort order so that the newer chapters, which are exclusively uploaded by Twisted Hel Scans, are at the top of the list

Furthermore, you can block MangaPlus group on MangaDex and it will stop appearing in the app too.
