### ISSUE TITLE
Edit/done button in chapter list takes multiple presses

### ISSUE THREAD

**Issue by henderea** [Paperback-iOS/app#268]
**Describe the bug**
In the chapter list, I often have to hit the edit or done button *several* times to get it to act.

**To Reproduce**
Go to a chapter list, and try hitting the edit button. Much of the time, it takes several attempts. Same with the done button you get once you finally get edit to work.

**Expected behaviour**
It should work on the first tap.

**App Version**
Eg: v0.4.0-b2.2.19 (but it started a few versions ago)

**Comment by ash10r** [comment]
Some additional information I’d like to add:

This seems to be a touch box issue for some buttons in the top right area. This includes:
-Edit/ done button on chapter list screen
-Open web view button on the manga/comic screen

the issue seems to be because of the touch box size. If I tap at the top right most corner of the word/icon (for eg the E of the word done) I can get it to work in 1 tap.

Issue currently present in:
Public build v 0.5.0 (1.0.3)

attaching image for reference
Highlighted area is the only part that actually registers touch:
![861B7938-8911-4011-BFF3-674420AADC3B](https://user-images.githubusercontent.com/78199278/111512023-4e544100-8775-11eb-9b5a-2f58ea5f6122.jpeg)

**Comment by FaizanDurrani** [comment]
Fixed in 0.7
