### ISSUE TITLE
[REQUEST] Integrate with cubari.moe

### ISSUE THREAD

**Issue by PythonCoderAS** [Paperback-iOS/app#286]
**Description**
Cubari.moe is a proxy service on top of imgur, nhentai, etc. They have a history service for the items you've read. I would like integration between https://cubari.moe/ and Paperback, especially with MangaDex down.

**How would it improve the App?**
I would be able to track history of manga chapters I read on Cubari and merge them with the main manga.

**Comment by ConradWeiser** [comment]
We're planning on implementing trackers in the near future, though unfortunately, this kind of service doesn't really act like a 'generic' tracker like Anilist, Myanimelist, or some of the other alternatives out there. 

I suppose with some careful planning, a source could be made for this, although it certainly wouldn't be ideal. Any community member with some development know-how could attempt that just fine. 

I'm not sure if we're intending on implementing this as a core-app feature, since it's a little.. Strange in nature. It doesn't offer a API of any kind as far as I can tell.

**Comment by PythonCoderAS** [comment]
Tachiyomi has an extension for it, (here)[https://tachiyomi.org/extensions/#all.cubari]. It should be possible, therefore, and you could probably inquire with guya.moe's developer (who also made cubari.moe), `appu#4444`.

**Comment by ConradWeiser** [comment]
If you refer to Tachiyomi's code [here](https://github.com/tachiyomiorg/tachiyomi-extensions/tree/master/src/all/cubari/src/eu/kanade/tachiyomi/extension/all/cubari) - I notice that they use some tricks which Paperback isn't capable of. Most notably the use of Webview and JS Latching.

Where Tachiyomi is very lax in the tools available to extension developers, due to the nature of Apple's kernel and Swift, there have been some design choices in the past leading us not to support things like that.

**Comment by PythonCoderAS** [comment]
I guess this will require cubari.moe to add in an API, or better yet, Paperback will need to be able to hook into Cubari's `remoteStorage` system and use that directly, which I suspect is the easier way to do this. Cubari itself is a proxy reader like Paperback, so it would be redundant to proxy a proxy.
