### ISSUE TITLE
[BUG] Can't have more than one device active at a time

### ISSUE THREAD

**Issue by Supster131** [Paperback-iOS/app#30]
If you login to Patreon on one device, you will be prompted to relogin on a previous device upon re-opening the app. This happens until you stop logging into Patreon on another device.

version: v0.2-wip.3

**Comment by FaizanDurrani** [comment]
Did this happen on earlier builds?

**Comment by Supster131** [comment]
Just went back and checked, yes. It does appear to happen on previous builds as well.

**Comment by FaizanDurrani** [comment]
Accidentally closed this.

**Comment by ConradWeiser** [comment]
Fixed in the current version of the app. 
Paperback will make a check once a day. Once you've made the check for the day, it will not do another check for 24 hours. 

If multiple devices register within the day, it will not kick your other devices off. (You simply will have to do another login once the day has passed)
