### ISSUE TITLE
[REQUEST] Allow multiple manga from the same source to be merged

### ISSUE THREAD

**Issue by PythonCoderAS** [Paperback-iOS/app#300]
**Description**
Some sources have multiple entries for the same manga. I should be able to merge these since there might be different chapters in each. They could be differentiated with an arbitrary number.

**How would it improve the App?**
It would make manga management much easier.

**Comment by ConradWeiser** [comment]
This seems a little niche and very specific. The overwhelming majority of sources that I'm aware about don't have this issue

**Comment by PythonCoderAS** [comment]
> This seems a little niche and very specific. The overwhelming majority of sources that I'm aware about don't have this issue

If we can merge multiple sources, it shouldn't be too much of a stretch to allow merging two mangas from one source.

**Comment by ConradWeiser** [comment]
This isn't an issue of technical implementation. It's more a concern as to the design goals of Paperback. Paperback isn't meant to be over complicated with loads of customization and little niche features. The merge function may confuse new readers as it is, if they aren't familiar with Tachiyomi or something of the sort. In this case, you may have people asking themselves the valid question of "What does the merge function do, really?" 

Being able to merge two manga from the same source implies that the merge view requires titles from the same source. This may lead users to try to use the merge function to simply create a collection of titles, instead of for what the function is intended for in the first place. 

I'm not claiming that this is a bad idea or anything. I'm simply suggesting that the user experience needs to be addressed from a user experience perspective. Not by a 'is the implementation feasible' perspective.

**Comment by FaizanDurrani** [comment]
As @ConradWeiser pointed it out, The feature does not fit the overall design and would not play nice with the tabbed chapter list since the the tab name would have to be the full title which causes various other problems.
