### ISSUE TITLE
[REQUEST] Support for reading local files.

### ISSUE THREAD

**Issue by WhonderWy** [Paperback-iOS/app#340]
**Description**
As a user, would like to see paperback support reading from *.cb* files. These files are `.zip` (cbz), `.rar` (cbr), `.7z` (cb7), `.tar` (cbt) files with different file extensions. 
Alternatively (or additionally), support reading directly from `zip`, `rar`, `7z` and `tar` archives and `pdf` files. 
Alternatively (or additionally), support viewing the (image) files directly.

This would entail adding a new tab or menu for local files or altering the library tab to include support for the local files. Furthermore, including support for the Files app would be appreciated as a means to transfer files into the application.

**How would it improve the App?**
Supporting local files would mean more use of the application.
Supporting local files would also mean that users would not need to use another application to read already downloaded content.
Supporting local files would also mean that Paperback doesn't have to rely on source extensions to increase its usage as local files don't entail supporting Paperback's API. 
Supporting local files would also mean that Paperback would see usage from other locales since local files aren't restricted by the languages supported by the currently existing sources.

**Additional context**
I have a big enough library of DRM-free "comic-book" archives from Humble Bundle, etc that I would like to be able to read them on a dedicated manga viewer application. None of them includes the viewer features I want, but it does look like Paperback would be closest to offering the features.
I'll add more later but I'm looking for something with CDisplayEX+alpha support for viewing. Support for "cover pages" is obvious. Two-page with no gaps, one-page modes; portrait and landscape support on the iPad is also a must. A slider to quickly move from page to page is also a must.
Once I experiment a bit more, I'll add to or remove from the list. I don't read from any of the sources available so pardon me for not knowing what Paperback already supports.

**Comment by ConradWeiser** [comment]
Hi @WhonderWy, thanks for the well written request!

We do not have plans for supporting local files directly. Paperback wasn't quite designed with that in mind, as the entire reader infrastructure relies on making network requests in order to pull images into memory. It never was in the design scope.

**HOWEVER**, there is definitely a workaround for reading local content, if you have your own library! 

In version 0.6 (which at the time of writing this is still unreleased, this will be the next update), we are introducing Stateful Sources. This allows extension developers to write sources which require login information, or may have other settings which a user would need to edit inside of the app in order to work correctly.

As such, once 0.6 hits, we will likely be replacing the default source (Currently the broken MangaDex) with [Komga](https://komga.org/)! Komga is a selfhosted service which can store and organize all of your local content. (CBZ files, PDFs, CBR, hell even EPUBS if you have book contents!) -- The app allow a user to input their IP address for Komga, and browse through your local files like it was a webservice! 

Other things such as a slider to move between pages may end up on our roadmap in the future, though before we get to the UI refinement stage, there are plenty of other features which we're hoping to complete for the app first. 

If Komga doesn't suit your fancy, if there is any other selfhosted service out there which can run your local content, an extension to hook into that will be made possible in that 0.6 update.

**Comment by proudbatdan** [comment]
I do not have a computer so I can not use Komga and the support for local files would allow me to read more things that aren’t manga in a pretty ui
