### ISSUE TITLE
[REQUEST]When merging sources it gives the option to select a collection instead of all manga

### ISSUE THREAD

**Issue by luism213** [Paperback-iOS/app#565]
**Description**
When merging a source it would give the option to select a collection in which that manga is in instead of just sending you to the all manga tab.

**How would it improve the App?**
For people like me who sort a large amount of manga into collections for easy finding this would make merging source easier. 

**Additional context**
I was thinking a view like clicking the library button at the bottom, how it takes you to chose either all manga or one of your collections. (if this is something already requested or planned in the next update I do apologized)

**Comment by XenitXTD** [comment]
@luism213 by default if you bookmark something it goes under the all manga tab, everything will always exist under the all manga section. The collection is just a way for your to segment and organize your manga in an easier to find way but if you wish to see everything it will be under all manga.

In the new reader in v0.7 if you add to library without adding to a collection the behaviour is the same

**Comment by luism213** [comment]
I understand that all manga is available in all manga by default; however what I suggest is when taking one source and merging it with another in your own library that instead of going straight into all manga it give the option to go into a chosen collection where the manga source you wish to merge is located.

**Comment by FaizanDurrani** [comment]
You're probably on an old build, update to 0.7 via TestFlight or https://github.com/Paperback-iOS/app/releases/tag/v0.7-r34

**Comment by luism213** [comment]
I am currently on 0.7 -r24 or which ever is on the discord right now.

**Comment by FaizanDurrani** [comment]
You're 10 builds behind, update using the link

**Comment by XenitXTD** [comment]
@luism213 First in V0.7 merge is practically dead... you have to bookmark a source and then go to that bookmarked one and add more sources... you cannot globally search and merge from there like in old version... not sure if this is intentional or not. I assume this is to bookmark from your preferred source and then add sources if and when you need them

second the old merge was tricky as it would not know where things are and what you were planning to merge with and made no assumptions so  it was generally easier to start a global search in all manga to merge... But essentially merge as known before where you would search and tap merge and lookup your library to merge is dead and now you would bookmark one and either while you are still in that view click to add additional sources which will start another search to add but cannot be selected in bulk and will be a one on one addition.

**Comment by luism213** [comment]
After updating the paperback app I can see what you guys were saying
