### ISSUE TITLE
[REQUEST]

### ISSUE THREAD

**Issue by 05k-44** [Paperback-iOS/app#606]
Something simple but would go a long way, having badges on manga to show how many unread and/or downloaded chapters it has attached to it.

Would make it easier to see if/when what manga has updated if not in the notifications as you got rid of them, and there is no update tab in the app, which could fit in with history if you add a tab menu in it.

**Comment by XenitXTD** [comment]
This is planned in v0.8 as some
Groundwork is needed to achieve this

It was not possible in the past due to multiple sources and not knowing what to track but there are plans to address this and show chapter counts and read/unread totals etc

Also there are several tickets already logged for this which are linked and pending

**Comment by XenitXTD** [comment]
#416 #249

**Comment by TheNetsky** [comment]
Duplicate
