### ISSUE TITLE
Status bar visible in the readers

### ISSUE THREAD

**Issue by FaizanDurrani** [Paperback-iOS/app#7]

**Comment by ConradWeiser** [comment]
Bar is always visible in latest iOS update, needs addressed again

**Comment by ConradWeiser** [comment]
According to various threads (Reddit, Apple Forums, etc.)
https://developer.apple.com/forums/thread/653153 

This seems to be a Swift bug. The implementation in the code seems correct and as intended, but since one of our levels uses a NavigationView, it naturally doesn't work on iOS 14+

We'll just leave this one as is for a while, and hopefully Apple fixes it in a Swift update at some point.

**Comment by FaizanDurrani** [comment]
Fixed in version 0.4.0 (2.2.9-Beta)
